name: GitHub Actions for Library Web app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx install poetry
        poetry install

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx install poetry
        poetry install

    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install diffutils curl jq

    - name: Run Python API tests
      run: |
        ./tests/api_tests.sh
